const WishlistActionTypes = {
  UNDO: 'UNDO',
  TOGGLE_ITEM_IN_WISHLIST: 'TOGGLE_ITEM_IN_WISHLIST',
  QUEUE_FOR_ADD: 'QUEUE_FOR_ADD',
  QUEUE_FOR_REMOVAL: 'QUEUE_FOR_REMOVAL',
  UPDATE_WISHLIST: 'UPDATE_WISHLIST',
  CLEAR_WISHLIST: 'CLEAR_WISHLIST',
  SHOW_POPUP: 'SHOW_POPUP',
  HIDE_POPUP: 'HIDE_POPUP'
};

export default WishlistActionTypes;