const WishlistActionTypes = {
  TOGGLE_ITEM_TO_WISHLIST: 'TOGGLE_ITEM_TO_WISHLIST',
  CLEAR_WISHLIST: 'CLEAR_WISHLIST',
  // CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART'
};

export default WishlistActionTypes;